### ISSUE TITLE
Cannot set parameter in INTERVAL statement (PostgreSQL)

### ISSUE THREAD

**Issue by nieldw** [seratch/kotliquery#34]
It seems it's not possible to set a parameter in a `INTERVAL '? SECONDS'` statement, using postgres:

This minimal test case:
``` kotlin
    @Test
    fun `should be able to replace parameters in INTERVAL statements`() {
        using(sessionOf(HikariCP.dataSource())) { session ->
            val query = queryOf(
                    """SELECT INTERVAL '? SECONDS' """.trimMargin(),
                    300)
                    .map { row -> row.string(1) }
                    .asSingle
            val interval: String? = session.run(query)
            assertEquals("00:05:00", interval)
        }
    }
```

Produces this stack trace:
``` text
org.postgresql.util.PSQLException: The column index is out of range: 1, number of columns: 0.

	at org.postgresql.core.v3.SimpleParameterList.bind(SimpleParameterList.java:65)
	at org.postgresql.core.v3.SimpleParameterList.setBinaryParameter(SimpleParameterList.java:132)
	at org.postgresql.jdbc.PgPreparedStatement.bindBytes(PgPreparedStatement.java:1007)
	at org.postgresql.jdbc.PgPreparedStatement.setInt(PgPreparedStatement.java:283)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.setInt(HikariProxyPreparedStatement.java)
	at kotliquery.Session.setParam(Session.kt:46)
	at kotliquery.Session.access$setParam(Session.kt:17)
	at kotliquery.Session.populateParams(Session.kt:213)
	at kotliquery.Session.createPreparedStatement(Session.kt:103)
	at kotliquery.Session.rows(Session.kt:107)
	at kotliquery.Session.single(Session.kt:123)
	at kotliquery.action.NullableResultQueryAction.runWithSession(NullableResultQueryAction.kt:12)
	at kotliquery.Session.run(Session.kt:183)
```

**Comment by seratch** [comment]
It doesn't seem to be an issue of this library but I guess this thread should be helpful. https://www.postgresql-archive.org/INTERVAL-parameter-in-PreparedStatement-worked-in-7-4-but-not-in-8-0-driver-td2169420.html

**Comment by seratch** [comment]
Let me close this issue now but feel free to write in if you have any follow ups!
