### ISSUE TITLE
Insertion of timestamps triggers namedParameter feature

### ISSUE THREAD

**Issue by joaomneto** [seratch/kotliquery#35]
When performing a simple insert like this one:

```insert into log (action, timestamp) values ('user logged in', '2019-01-01 00:00:00')```

A jdbc error is triggered because the replacementMap in the `Query` object is initialized with the `:00` params as if they were really params.

The following error insues:

```
java.sql.SQLException: Parameter index out of range (1 > number of parameters, which is 0).

	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
	at com.mysql.cj.jdbc.ClientPreparedStatement.checkBounds(ClientPreparedStatement.java:1402)
	at com.mysql.cj.jdbc.ClientPreparedStatement.getCoreParameterIndex(ClientPreparedStatement.java:1415)
	at com.mysql.cj.jdbc.ClientPreparedStatement.setNull(ClientPreparedStatement.java:1680)
	at kotliquery.Session$populateParams$1.accept(Session.kt:251)
	at kotliquery.Session$populateParams$1.accept(Session.kt:18)
	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
	at kotliquery.Session.populateParams(Session.kt:81)
	at kotliquery.Session.createPreparedStatement(Session.kt:106)
	at kotliquery.Session.execute(Session.kt:181)
	at kotliquery.action.ExecuteQueryAction.runWithSession(ExecuteQueryAction.kt:9)
	at kotliquery.Session.run(Session.kt:208)
```

A simple fix for this would be to disallow digits as the first character of the named parameter and adjust the regex that finds them in the query statements.

**Comment by seratch** [comment]
Fixed by #36 . Kotliquery 1.3.1 includes the change.
