### ISSUE TITLE
Usage of colon in a comment tries to bind it as a variable

### ISSUE THREAD

**Issue by busches** [seratch/kotliquery#47]
If I execute a query that has a comment that contains a colon, kotliquery attempts to use that colon as a bind parameter and we get the following error:
```
The column index is out of range: 1, number of columns: 0.
org.postgresql.util.PSQLException: The column index is out of range: 1, number of columns: 0.
	at org.postgresql.jdbc.PgPreparedStatement.setNull(PgPreparedStatement.java:192)
	at kotliquery.Session.populateParams$lambda-1(Session.kt:291)
	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:721)
	at kotliquery.Session.populateParams(Session.kt:91)
	at kotliquery.Session.createPreparedStatement(Session.kt:116)
	at kotliquery.Session.execute(Session.kt:204)
	at kotliquery.action.ExecuteQueryAction.runWithSession(ExecuteQueryAction.kt:9)
	at kotliquery.Session.run(Session.kt:231)
```

Reproduction:
```kotlin
val sql = """
-- Some dumb comment :shrug:
SELECT 1;
"""

val url = "jdbc:postgresql://$host:$port/$database"
val dbSession = sessionOf(url, username, password)

using(dbSession) { session ->
    session.run(queryOf(sql, emptyMap()).asExecute)
}
```

Executing the same code straight against Postgres does not fail, as the commented out code is properly ignored.

Kotliquery version: 1.6.1

**Comment by seratch** [comment]
Hi @busches, thanks for reporting this issue. To resolve this issue, the named parameter feature https://github.com/seratch/kotliquery/issues/10 should have great consideration of comments.

**Comment by busches** [comment]
Yea, I'm not following what you mean. This is a bug in the named parameter feature.

**Comment by seratch** [comment]
> I'm not following what you mean

Oh, was my comment confusing? To make my above comment clearer, I meant that the named parameter feature should be improved to support comment parts properly. I'm sure that we are on the same page.
